server:
  port: 8084

spring:
  application:
    name: transfer-app
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bank_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:qwerty}

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: ${TRANSFER_DB_SCHEMA:transfer_schema}

  jpa:
    properties:
      hibernate:
        default_schema: ${TRANSFER_DB_SCHEMA:transfer_schema}
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          transfer-app:
            provider: keycloak
            client-id: transfer-app
            client-secret: transfer-app-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm

bank:
  account-gateway:
    base-url: http://localhost:8086/accounts
  notification-gateway:
    base-url: http://localhost:8086/notification

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO