apiVersion: v2
name: app-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgres-chart
    version: 0.1.0
  - name: account-chart
    repository: "file://charts/account-chart"
    condition: account-chart.enabled
    version: 0.1.0
  - name: cash-chart
    repository: "file://charts/cash-chart"
    condition: cash-chart.enabled
    version: 0.1.0
  - name: notification-chart
    repository: "file://charts/notification-chart"
    condition: notification-chart.enabled
    version: 0.1.0
  - name: transfer-chart
    repository: "file://charts/transfer-chart"
    condition: transfer-chart.enabled
    version: 0.1.0