apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-chart.fullname" . }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "postgres-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
