apiVersion: v1
data:
  password: cXdlcnR5
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: {{ include "account-chart.fullname" . }}-secret
  labels:
    {{- include "account-chart.labels" . | nindent 4 }}

stringData:
  POSTGRES_DB: "bank_db"


