server:
  port: 8085

spring:
  application:
    name: notification-app

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bank_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:qwerty}

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: ${NOTIFICATION_DB_SCHEMA:notification_schema}

  jpa:
    properties:
      hibernate:
        default_schema: ${NOTIFICATION_DB_SCHEMA:notification_schema}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
