CREATE SCHEMA IF NOT EXISTS account_schema;
CREATE TABLE account_schema.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    name VARCHAR(255),
    birth_date DATE,
    balance DECIMAL(19,2)
);