server:
  port: 8082

spring:
  application:
    name: account-app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: ${ACCOUNT_DB_SCHEMA:account_schema}

  jpa:
    properties:
      hibernate:
        default_schema: ${ACCOUNT_DB_SCHEMA:account_schema}
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/bank-realm}
          #issuer-uri: http://host.docker.internal:8080/realms/bank-realm
      client:
        registration:
          account-app:
            provider: keycloak
            client-id: account-app
            client-secret: account-app-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank-realm}
            #issuer-uri: http://host.docker.internal:8080/realms/bank-realm

bank:
  notification-gateway:
    base-url: http://localhost:8086/notification

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO