apiVersion: v1
kind: Service
metadata:
  name: {{ include "cash-chart.fullname" . }}
  labels:
    {{- include "cash-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
      nodePort: {{ .Values.nodePortService.port }}
  selector:
    {{- include "cash-chart.selectorLabels" . | nindent 4 }}
